### PR TITLE
Updates dependencies, changes to support newer Rubies 2.6+

### PR DESCRIPTION
**Pull request by stevegeek**
First PR is maintenance to unitwise to:

- add support for newer Rubies (2.6+) 
- tests against them and latest JRuby and TruffleRuby
- drops support for older ones (even 2.6 is EOL now but thats very recent so keeping it for now)
- updates dependencies
- moves to Github Actions and dependabot for CI and dep audits

Some notes on the changes:

1. `BigDecimal.new` was deprecated and later removed from Ruby 2.6 onwards so just dropped the use of it.
2. `psych` 4 is now used in Ruby 3 and raises on `#load` when encountering `BigDecimals` in the YAML. Since the unit data files are part of the gem and thus 'trusted' I changed to use `unsafe_load` rather than be explicit with `permitted_classes`.

A next PR will fix warnings and deprecations from minitest

Opening as a Draft for now in case we need to discuss anything first.

### CODE REVIEW

**Comment by petergoldstein** [comment]
I'm not sure you want the `.ruby-version` file to be checked in, but if you do you may want to update to `3.1.2` which was just released.

**Comment by stevegeek** [comment]
Thanks @petergoldstein , yeah I'm not sure we want it in there at all.

**Comment by petergoldstein** [comment]
@joshwlewis Any chance we can get this reviewed and merged?  Thanks.

**Review by joshwlewis — APPROVED** [review]
Looks great, thanks!

**Comment by stevegeek** [comment]
@joshwlewis Thanks for the review, will do!

**Comment by stevegeek** [comment]
@joshwlewis all ok with this PR?

**Comment by stevegeek** [comment]
@joshwlewis friendly nudge, just wondering if we might move forward with some of the updates? Thanks!

**Comment by floriandejonckheere** [comment]
@joshwlewis Looks like the PR if complete now, can this be merged? Thanks!

**Comment by joshwlewis** [comment]
Thanks for the patience, y'all!

**Pull request merged**
