### PR TITLE
Prevent floating point accuracy loss

### PR DESCRIPTION
**Pull request by joshwlewis**
There have been several reports of floating point accuracy loss with some of the higher precision units. There are some examples in #27, #35, and #42.

This PR addresses those issues by:

1. Serializing UCUM data as either `BigDecimal` or `Integer`, not `Float`.
2. Not performing `BigDecimal(float.to_s)` when initializing base and derived units
3. Performing mathematical operations on `Rational`s rather than `Float`s and `BigDecimal`s.

### CODE REVIEW

**Comment by phlegx** [comment]
Hi @joshwlewis nice work. Can this be merged in master and released?

**Comment by joshwlewis** [comment]
Yes, I plan on releasing this soon. There are tests failing for JRuby (as @k3rn31 found), but it looks like a bug within JRuby itself. I've opened an issue here: https://github.com/jruby/jruby/issues/4711. I plan on adding a workaround for that on this PR.

**Comment by phlegx** [comment]
@joshwlewis  should the float numbers here [lib/unitwise/functional.rb](https://github.com/joshwlewis/unitwise/blob/master/lib/unitwise/functional.rb) also be BigDecimal?

**Comment by joshwlewis** [comment]
> @joshwlewis should the float numbers here lib/unitwise/functional.rb also be BigDecimal?

I think so, yes. Feel free to open a PR if you are so inclined.

**Comment by joshwlewis** [comment]
They might actually need to be `Rational`. Even `BigDecimal` operations can have accuracy loss.

**Pull request merged**
